export const GET_SHOP_CARDS = 'GET_SHOP_CARDS'
export const ADD_SHOP_CARD = 'ADD_SHOP_CARD'
export const REMOVE_SHOP_CARD_AMOUNT = 'REMOVE_SHOP_CARD_AMOUNT'

export const GET_CART_CARDS = 'GET_CART_CARDS'
export const ADD_CART_CARD = 'ADD_CART_CARD'
export const REMOVE_CART_CARD_AMOUNT = 'REMOVE_CART_CARD_AMOUNT'
